### ISSUE TITLE
recoil-nexus does not work with recoil 0.5.2

### ISSUE THREAD

**Issue by micktg** [luisanton-io/recoil-nexus#10] opened 2021-11-04 14:45 UTC
I just updated to recoil 0.5.0, and I got the error message, that a recoil state update outside a component is not possible with recoil-nexus 0.3.4. I reverted to recoil 0.4.1 and everything works again as expected, so I assume there is a incompatibility for recoil-nexus with the latest recoil 0.5.0 version.

**Comment by luisanton-io** [comment] 2021-11-04 14:56
Thanks for letting me know. Things do get broken sometimes on new releases.
I'll be on it asap.
L

**Comment by micktg** [comment] 2021-11-04 15:01
Awesome! And thanks for the great project!

**Comment by luisanton-io** [comment] 2021-11-04 15:42
`recoil-nexus` v0.3.8 works for me now with `recoil` 0.5.0

[Demo sandbox](https://codesandbox.io/s/quirky-euclid-qnvzw)
Hope it helps!
L

**Comment by micktg** [comment] 2021-11-04 16:36
Ah, I missed the update for v0.3.8. I usually have a subscription on the projects GitHubs release page for new releases. But at your project, there are no releases, so I missed the update. My bad, sorry.

**Comment by luisanton-io** [comment] 2021-11-04 17:51
@micktg actually v0.3.8 was released because of this issue: so thank you!
L

**Comment by micktg** [comment] 2021-11-08 14:52
Hi Luis, I just upgraded to Recoil v0.5.2 and recoil nexus with v0.3.8 stops working again. Same error as before: 
`Uncaught Error: This component must be used inside a <RecoilRoot> component.`

**Comment by luisanton-io** [comment] 2021-11-08 16:56
Fixed once and for all on v0.3.9
It was a mistake of mine on the `package.json`
Thanks for the heads up!
L

**Closed by luisanton-io** 2021-11-08 16:56 UTC

**Comment by micktg** [comment] 2021-11-08 22:53
I tested it and it works! Thank you.

**Comment by croossin** [comment] 2022-01-16 22:23
I seem to be having the same issue on 0.5.2 and 0.3.14... is it confirmed to be working?

**Comment by luisanton-io** [comment] 2022-01-16 23:52
Hi @croossin 0.5.2 and 0.3.14 are working here, which error are you getting exactly? 
Did you remember to add the `<RecoilNexus />` component under your `<RecoilRoot>`?
L

**Comment by micktg** [comment] 2022-01-25 12:51
I can also confirm that everything works fine with
```
"recoil": "0.5.2",
"recoil-nexus": "0.3.15",
```
